services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: utakata
      POSTGRES_PASSWORD: 1336
      POSTGRES_DB: utakata_db
    ports:
      - 12345:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true
    restart: always

volumes:
  postgres_data: